from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import HexColor

styles = getSampleStyleSheet()

title_style = styles["Heading1"]
title_style.alignment = TA_CENTER
title_style.textColor = HexColor("#2563EB")

heading_style = styles["Heading2"]
heading_style.textColor = HexColor("#1D4ED8")

normal_style = styles["BodyText"]


def create_career_report(
    filename,
    summary,
    progress,
    history
):

    doc = SimpleDocTemplate(filename)

    story = []

    # ----------------------------------
    # Title
    # ----------------------------------

    story.append(
        Paragraph(
            "AI Career Coach Report",
            title_style
        )
    )

    story.append(Spacer(1, 20))

    # ----------------------------------
    # Overall Summary
    # ----------------------------------

    story.append(
        Paragraph(
            "Career Summary",
            heading_style
        )
    )

    story.append(
        Paragraph(
            f"<b>Total Questions:</b> {summary['total_questions']}",
            normal_style
        )
    )

    story.append(
        Paragraph(
            f"<b>Average Score:</b> {summary['average_score']}/10",
            normal_style
        )
    )

    story.append(Spacer(1, 20))

    # ----------------------------------
    # Strong Topics
    # ----------------------------------

    story.append(
        Paragraph(
            "Strong Topics",
            heading_style
        )
    )

    if summary["strong_topics"]:

        for topic in summary["strong_topics"]:

            story.append(
                Paragraph(
                    f"• {topic}",
                    normal_style
                )
            )

    else:

        story.append(
            Paragraph(
                "No strong topics available.",
                normal_style
            )
        )

    story.append(Spacer(1, 20))

    # ----------------------------------
    # Weak Topics
    # ----------------------------------

    story.append(
        Paragraph(
            "Weak Topics",
            heading_style
        )
    )

    if summary["weak_topics"]:

        for topic in summary["weak_topics"]:

            story.append(
                Paragraph(
                    f"• {topic}",
                    normal_style
                )
            )

    else:

        story.append(
            Paragraph(
                "No weak topics available.",
                normal_style
            )
        )

    story.append(Spacer(1, 20))

    # ----------------------------------
    # Progress
    # ----------------------------------

    story.append(
        Paragraph(
            "Overall Progress",
            heading_style
        )
    )

    story.append(
        Paragraph(
            f"<b>Total Interview Questions:</b> {progress['total_questions']}",
            normal_style
        )
    )

    story.append(
        Paragraph(
            f"<b>Average Interview Score:</b> {progress['average_score']}",
            normal_style
        )
    )

    story.append(Spacer(1, 20))

    # ----------------------------------
    # Interview History
    # ----------------------------------

    story.append(
        Paragraph(
            "Interview History",
            heading_style
        )
    )

    for item in history:

        story.append(
            Paragraph(
                f"""
                <b>Role:</b> {item.role}<br/>
                <b>Topic:</b> {item.topic}<br/>
                <b>Score:</b> {item.score}/10
                """,
                normal_style
            )
        )

        story.append(Spacer(1, 10))

    # ----------------------------------
    # Footer
    # ----------------------------------

    story.append(Spacer(1, 30))

    story.append(
        Paragraph(
            "<b>Generated by AI Career Coach</b>",
            title_style
        )
    )

    doc.build(story)