import { useEffect, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import api from "../api";
import "./Interview.css";

function Interview() {
  const { state } = useLocation(); const navigate = useNavigate();
  const role = state?.role || "AI Engineer";
  const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState(""); const [evaluation, setEvaluation] = useState(null);
  const [loading, setLoading] = useState(false); const [difficulty, setDifficulty] = useState("Medium"); const [totalQuestions, setTotalQuestions] = useState(5);
  const [interviewId, setInterviewId] = useState(""); const [questionNumber, setQuestionNumber] = useState(1); const [timeLeft, setTimeLeft] = useState(300); const [error, setError] = useState("");
  useEffect(() => { if (!question) return undefined; const timer = setInterval(() => setTimeLeft((value) => Math.max(0, value - 1)), 1000); return () => clearInterval(timer); }, [question]);
  const formattedTime = `${String(Math.floor(timeLeft / 60)).padStart(2, "0")}:${String(timeLeft % 60).padStart(2, "0")}`;
  const startInterview = async () => { setLoading(true); setError(""); try { const { data } = await api.post("/start-interview", { role, skills: [], difficulty, total_questions: totalQuestions }); setQuestion(data.data.question); setInterviewId(data.interview_id); setQuestionNumber(1); setTimeLeft(300); } catch { setError("We couldn’t start the interview. Please check the API and try again."); } finally { setLoading(false); } };
  const submitAnswer = async () => { if (!answer.trim()) { setError("Write an answer before submitting."); return; } setLoading(true); setError(""); try { const { data } = await api.post("/chat-interview", { interview_id: interviewId, role, question, answer, difficulty, question_number: questionNumber, total_questions: totalQuestions }); setEvaluation(data.evaluation); setAnswer(""); if (data.completed) { setQuestion(""); setTimeout(() => navigate("/summary"), 1400); } else { setQuestion(data.next_question.question); setQuestionNumber(data.question_number); setTimeLeft(300); } } catch { setError("We couldn’t evaluate that answer. Please try again."); } finally { setLoading(false); } };
  const progress = ((question ? questionNumber : 0) / totalQuestions) * 100;
  return <main className="page-shell interview-container"><header><p className="eyebrow">Interview studio</p><h1 className="page-title">Practice with purpose.</h1><p className="page-subtitle">A focused mock interview for <strong>{role}</strong>, with immediate feedback after every response.</p></header>
    <section className="interview-layout"><aside className="interview-sidebar surface"><span className="role-label">Target role</span><h2>{role}</h2>{question ? <><div className="timer-label">Time remaining</div><div className={timeLeft < 60 ? "timer urgent" : "timer"}>{formattedTime}</div><div className="progress-meta"><span>Question {questionNumber} of {totalQuestions}</span><span>{Math.round(progress)}%</span></div><div className="progress-bar"><span style={{ width: `${progress}%` }} /></div></> : <div className="session-settings"><label>Difficulty<select value={difficulty} onChange={(e) => setDifficulty(e.target.value)}><option>Easy</option><option>Medium</option><option>Hard</option></select></label><label>Questions<select value={totalQuestions} onChange={(e) => setTotalQuestions(Number(e.target.value))}><option value={5}>5 questions</option><option value={10}>10 questions</option><option value={15}>15 questions</option></select></label><button className="button" onClick={startInterview} disabled={loading}>{loading ? "Starting…" : "Start practice"}</button></div>}</aside>
      <section className="question-panel surface">{question ? <><p className="eyebrow">Current question</p><h2>{question}</h2><textarea className="answer-box" value={answer} onChange={(e) => setAnswer(e.target.value)} placeholder="Structure your answer clearly. Include examples where useful." /><div className="answer-actions"><span>{answer.length} characters</span><div><button className="button button-secondary" onClick={() => navigate("/summary")}>End session</button><button className="button" onClick={submitAnswer} disabled={loading}>{loading ? "Evaluating…" : "Submit answer"}</button></div></div></> : <div className="empty-session"><span>◎</span><h2>Set up your practice session</h2><p>Choose a difficulty and session length, then we’ll generate your first question.</p></div>}{error && <p className="form-error">{error}</p>}{evaluation && <article className="feedback-card"><div><p className="eyebrow">Latest feedback</p><h3>Score: {evaluation.score}/10</h3></div><p>{evaluation.feedback}</p><details><summary>View a strong answer</summary><p>{evaluation.correct_answer}</p></details>{evaluation.improvement_points?.length > 0 && <ul>{evaluation.improvement_points.map((point, index) => <li key={index}>{point}</li>)}</ul>}</article>}</section></section></main>;
}
export default Interview;
